language: node_js
node_js:
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "node"
cache:
    directories:
        - "node_modules"
before_script:
    - "npm install"
script:
    - "npm run-script coveralls"
after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
